name: Build

on:
  push:
    branches: [ "master" ]
  
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        make
        mkdir output
        mv KrxkCompiler output/
        cp test.in output/

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        # Artifact name
        name: lex-bison
        # A file, directory or wildcard pattern that describes what to upload
        path: output

    - name: Start SSH via tmate
      uses: P3TERX/ssh2actions@main
      # Send connection info to Telegram (optional)
      # You can find related documents here: https://core.telegram.org/bots
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
              

