name: Makefile CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        make
        mkdir output
        mv KrxkCompiler output/
        cp test.in output/
        tar -cvzf Output.tar.gz output/

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        # Artifact name
        name: lex-bison
        # A file, directory or wildcard pattern that describes what to upload
        path: Output.tar.gz
        
    - name: Upload to release
      uses: JasonEtco/upload-to-release@master
      with:
        args: Output.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              

